# @package _global_
model:
  model_source: /share/pierson/matt/zoo/models/Qwen3-8B
  model_family: qwen3
  embedding_model_source: /share/pierson/matt/zoo/models/Qwen3-Embedding-8B
  chat_template_kwargs:
    enable_thinking: false
  engine_kwargs:
    tensor_parallel_size: 1
    max_model_len: 8192
  batch_size: 0
  concurrency: 1
