model_source: /share/pierson/matt/zoo/models/Qwen2.5-72B-Instruct
engine_kwargs:
  enable_chunked_prefill: true
  max_num_batched_tokens: 4096
  max_model_len: 32768
  gpu_memory_utilization: 0.9
  tensor_parallel_size: 4
  enable_prefix_caching: true
  disable_log_stats: true
  enforce_eager: true
batch_size: 1
concurrency: 1
