#!/usr/bin/env python3
"""Generate per-ablation model YAMLs from SFT pair-ablation multirun roots.

For each ablation subdir (``ctx-{T,F}_appr-{T,F}_norms-{T,F}_conf-{T,F}``)
under one or more multirun roots, emit a model YAML that wires the LoRA
adapter at ``<ablation>/sft_only/outputs/sft/checkpoint`` into vLLM. The
output path is

    dagspaces/common/conf/model/<family>/<variant>/<ablation>.yaml

where ``<family>/<variant>`` (e.g. ``qwen3.5-9b/base``) is read from
``hydra.runtime.choices.model`` in the root's ``multirun.yaml`` — so base
and instruct sweeps land in non-colliding subfolders without any hardcoding.

Usage::

    # Default roots = yesterday's two ablation sweeps. Dry-run by default.
    python scripts/generate_ablation_model_yamls.py
    python scripts/generate_ablation_model_yamls.py --write

    # Custom roots:
    python scripts/generate_ablation_model_yamls.py --write \\
        multirun/2026-04-28_sft_pair_ablation/18-34-09 \\
        multirun/2026-04-28_sft_pair_ablation/20-11-11
"""
from __future__ import annotations

import argparse
import copy
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
MODEL_CONF_DIR = REPO / "dagspaces/common/conf/model"

DEFAULT_ROOTS = [
    REPO / "multirun/2026-04-28_sft_pair_ablation/18-34-09",
    REPO / "multirun/2026-04-28_sft_pair_ablation/20-11-11",
]

ABLATION_RE = re.compile(
    r"^ctx-(?:True|False)_appr-(?:True|False)_norms-(?:True|False)_conf-(?:True|False)$"
)


def read_root_choice(root: Path) -> tuple[str, str]:
    """Return (family, variant) from a multirun root's multirun.yaml.

    e.g. 'qwen3.5-9b/base' -> ('qwen3.5-9b', 'base').
    """
    mr_path = root / "multirun.yaml"
    if not mr_path.exists():
        raise FileNotFoundError(f"missing multirun.yaml under {root}")
    mr = yaml.safe_load(mr_path.read_text())
    choice = mr["hydra"]["runtime"]["choices"]["model"]
    if "/" not in choice:
        raise ValueError(
            f"unexpected model choice {choice!r} in {mr_path} (expected family/variant)"
        )
    family, variant = choice.split("/", 1)
    return family, variant


def load_source_model(family: str, variant: str) -> dict:
    """Load the base model YAML the ablations are derived from."""
    src = MODEL_CONF_DIR / family / f"{variant}.yaml"
    if not src.exists():
        raise FileNotFoundError(
            f"source model yaml not found: {src} — needed as template for LoRA variants"
        )
    doc = yaml.safe_load(src.read_text())
    if "model" not in doc:
        raise ValueError(f"{src} has no top-level 'model' key")
    return doc


def build_ablation_doc(source_doc: dict, checkpoint_path: Path) -> dict:
    """Produce the YAML doc for one ablation by adding LoRA fields to the source."""
    doc = copy.deepcopy(source_doc)
    model = doc["model"]
    # Insert lora_path right after model_family to match sft-ci.yaml layout.
    items = list(model.items())
    new_model: dict = {}
    for k, v in items:
        new_model[k] = v
        if k == "model_family":
            new_model["lora_path"] = str(checkpoint_path)
    if "lora_path" not in new_model:
        new_model["lora_path"] = str(checkpoint_path)
    doc["model"] = new_model
    model = new_model
    eng = model.setdefault("engine_kwargs", {})
    eng["enable_lora"] = True
    eng["max_lora_rank"] = 64
    eng["enforce_eager"] = True
    # sft-ci.yaml uses max_num_seqs=16 with LoRA; match that for consistency.
    eng["max_num_seqs"] = 16
    return doc


def render_yaml(doc: dict, provenance_dir: Path) -> str:
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, indent=2)
    return (
        "# @package _global_\n"
        "# Auto-generated by scripts/generate_ablation_model_yamls.py — do not edit by hand.\n"
        f"# Source run artifact: {provenance_dir}\n"
        + body
    )


def discover_ablations(root: Path) -> list[Path]:
    return sorted(
        p for p in root.iterdir() if p.is_dir() and ABLATION_RE.match(p.name)
    )


def process_root(
    root: Path, *, write: bool, force: bool
) -> tuple[int, int, int]:
    """Returns (n_written, n_skipped_missing_ckpt, n_skipped_exists)."""
    family, variant = read_root_choice(root)
    source_doc = load_source_model(family, variant)
    out_dir = MODEL_CONF_DIR / family / variant
    print(f"[{root.name}] family={family} variant={variant} -> {out_dir.relative_to(REPO)}/")

    n_written = n_missing = n_exists = 0
    ablations = discover_ablations(root)
    if not ablations:
        print(f"  (no ablation subdirs found under {root})")
        return 0, 0, 0

    for ab_dir in ablations:
        ckpt = ab_dir / "sft_only" / "outputs" / "sft" / "checkpoint"
        if not (ckpt / "adapter_config.json").exists():
            print(f"  SKIP {ab_dir.name}: no adapter_config.json under {ckpt}")
            n_missing += 1
            continue

        doc = build_ablation_doc(source_doc, ckpt.resolve())
        text = render_yaml(doc, ab_dir.resolve())
        out_path = out_dir / f"{ab_dir.name}.yaml"

        if out_path.exists() and not force:
            print(f"  EXISTS {out_path.relative_to(REPO)} (use --force to overwrite)")
            n_exists += 1
            continue

        if write:
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path.write_text(text)
            print(f"  WROTE  {out_path.relative_to(REPO)}")
        else:
            print(f"  PLAN   {out_path.relative_to(REPO)}")
        n_written += 1

    return n_written, n_missing, n_exists


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "roots",
        nargs="*",
        type=Path,
        help="Multirun root directories. Defaults to yesterday's two SFT pair ablation sweeps.",
    )
    ap.add_argument(
        "--write",
        action="store_true",
        help="Actually write files. Without this, the script only prints what it would do.",
    )
    ap.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing target YAMLs.",
    )
    args = ap.parse_args(argv)

    roots = args.roots or DEFAULT_ROOTS
    roots = [r if r.is_absolute() else (REPO / r).resolve() for r in roots]

    total_w = total_m = total_e = 0
    for root in roots:
        if not root.is_dir():
            print(f"ERROR: not a directory: {root}", file=sys.stderr)
            return 2
        w, m, e = process_root(root, write=args.write, force=args.force)
        total_w += w
        total_m += m
        total_e += e

    verb = "wrote" if args.write else "would write"
    print(
        f"\nSummary: {verb} {total_w} yaml(s); skipped {total_m} missing-checkpoint, "
        f"{total_e} already-exists. "
        + ("(dry run; pass --write to persist)" if not args.write else "")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
